# Random Numbers 

We will explore:
1. The sources of randomness in applied Machine Learning with a focus on algorithmq. 
2. What a pseudorandom number generator is and how to use them in Python.
3. When to control the sequence of random numbers and when to control for randomness.

7 parts:
- Randomness in Machine Learning
- Pseudorandom number generators 
- Random numbers in Python 
- Random numbers with NumPy 
- When to seed the random number generator 
- How to Control to Randomness 
- Common Questions 

In [3]:
# Seed the random number generator

# seed the pseudo random number generator 
from random import seed 
from random import random

# seed number generator 
seed(1)

# generate some random numbers
print(random(), random (), random())

# reset the seed 
seed(1)

print(random(), random(), random())

0.13436424411240122 0.8474337369372327 0.763774618976614
0.13436424411240122 0.8474337369372327 0.763774618976614


In [4]:
# Random Floating Points Value

# generate random floating points value 
from random import seed
from random import random 

# seed random number generator 
seed(1)

# generate 10 numbers between 0 and 1 
for _ in range(10):
    value = random()
    print(value)

0.13436424411240122
0.8474337369372327
0.763774618976614
0.2550690257394217
0.49543508709194095
0.4494910647887381
0.651592972722763
0.7887233511355132
0.0938595867742349
0.02834747652200631


In [7]:
# Generate Random Integer Value

# generate random inetger values 
from random import seed
from random import randint 

# seed random number generator 
seed(1)

# generate some integers 
for _ in range(10):
    value = randint(0, 10) 
    print(value)

2
9
1
4
1
7
7
7
10
6


In [8]:
# Random Gaussian Values

# generate random gaussian values 
from random import seed
from random import gauss

# seed radnom number generator
seed(1)

# generate some gaussian values 
for _ in range(10):
    value = gauss(0, 1)
    print(value)

1.2881847531554629
1.449445608699771
0.06633580893826191
-0.7645436509716318
-1.0921732151041414
0.03133451683171687
-1.022103170010873
-1.4368294451025299
0.19931197648375384
0.13337460465860485


In [10]:
# Random chosing from a list 

# generate random element from a list 
from random import seed
from random import choice

# seed the random number generator 
seed(1) 

# generate a sequence of 20 numbers 
sequence = [i for i in range(20)]
print(sequence)

# make a choice from sequence
for _ in range(5):
    selection = choice(sequence)
    print(selection)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
4
18
2
8
3


In [13]:
# Random subsample from a list 

# generate random sample without replacement 
from random import seed 
from random import sample 

# seed the random number generator 
seed(1) 

# generate a sequence 
sequence = [i for i in range(20)]
print(sequence)

# make a choice from sequence 
subset = sample(sequence, 5)
print(subset)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[4, 18, 2, 8, 3]


In [14]:
# Randomy Shuffle a List 

# randomly shuffle a sequence 
from random import seed
from random import shuffle

# seed teh random number generator 
seed(1) 

# generate a sequence 
sequence = [i for i in range(20)]
print(sequence)

# shuffle the list
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[11, 5, 17, 19, 9, 0, 16, 1, 15, 6, 10, 13, 14, 12, 7, 3, 8, 2, 18, 4]


In [15]:
# Random Number Generator (NumPy) 

# seed the random number generator 
from numpy.random import seed 
from numpy.random import rand 

# seed the random number generator 
seed(1) 

# generate some random numbers 
print(rand(3))

# reset the seed
seed(1) 

# generate some random numbers
print(rand(3))

[  4.17022005e-01   7.20324493e-01   1.14374817e-04]
[  4.17022005e-01   7.20324493e-01   1.14374817e-04]


In [22]:
# Array of random generated numbers (floating points, inetgers, gaussian values)

# seed the random number generator 
from numpy.random import seed
from numpy.random import rand
from numpy.random import randint
from numpy.random import randn 
from numpy.random import shuffle

# seed the random number generator
seed(1) 

# generate some random numbers 
value_rand = rand(10)
value_randint = randint(0, 10, 20)
value_gauss = randn(10)

print(value_rand) 
print(value_randint) 
print(value_gauss)

[  4.17022005e-01   7.20324493e-01   1.14374817e-04   3.02332573e-01
   1.46755891e-01   9.23385948e-02   1.86260211e-01   3.45560727e-01
   3.96767474e-01   5.38816734e-01]
[5 2 4 2 4 7 7 9 1 7 0 6 9 9 7 6 9 1 0 1]
[-0.17242821 -0.87785842  0.04221375  0.58281521 -1.10061918  1.14472371
  0.90159072  0.50249434  0.90085595 -0.68372786]


In [23]:
# Shuffle NumPy array 

# randomly shuffle a sequence 
from numpy.random import seed
from numpy.random import shuffle 

# seed random number generator
seed(1)

# prepare a sequence
sequence = [i for i in range(20)]

print(sequence)

# randomly shuffle the sequence
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[3, 16, 6, 10, 2, 14, 4, 17, 7, 1, 13, 0, 19, 18, 9, 15, 8, 12, 11, 5]
